name: Feature request
description: Suggest an idea for this project
title: "[Feature] "
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verification steps
      description: "
在提交之前，请确认
Please verify that you've followed these steps
"
      options:
        - label: "
我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 中找过我要提出的请求
I have searched on the [Issue Tracker](https://github.com/j178/leetgo/issues) for a related feature request.
"
          required: true
  - type: textarea
    attributes:
      label: Description
      description: 请详细、清晰地表达你要提出的论述，例如这个问题如何影响到你？你想实现什么功能？
    validations:
      required: true
